services:
  api : 
    build : 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    volumes: 
      - ./backend:/backend
    container_name: api
    networks:
      - app_network
    restart: always
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/frontend
    container_name: frontend
    networks:
      - app_network
    restart: always
networks:
  app_network:
    driver: bridge