name: Build & Deploy to Scaleway
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Scaleway Container Registry
      run:  echo ${{ secrets.SCW_SECRET_KEY}} | docker login rg.fr-par.scw.cloud/atut-group-1 -u ${{secrets.SCW_SECRET_KEY}} --password-stdin
    - name: Build the Docker image - Backend
      working-directory: ./backend
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend:v0
    - name: Push the Docker Image - Backend
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend:v0
    - name: Build the Docker image - Frontend
      working-directory: ./frontend
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/frontend:v0
    - name: Push the Docker Image - Frontend
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/frontend:v0

    