name: Build & Deploy to Scaleway

on:
  push:
    branches:
      - tag-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Echo Secret
        run: echo "${{secrets.SCW_SECRET_KEY}}"

      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh


      - name: Login to Scaleway Container Registry
        run: ./scripts/docker-login.sh

      - name: Build the Docker image - Backend
        run: ./scripts/build-backend.sh

      - name: Build the Docker image - Frontend
        run: ./scripts/build-frontend.sh


      - name: Tag the Docker Images
        run: ./scripts/tag.sh

      - name: Push the Docker Images
        run: ./scripts/push-images.sh


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: ./scripts/deploy.sh
